@startuml
'https://plantuml.com/use-case-diagram

(Gatherer) as (Gath)
(Order) as (Ord)
(Fundamental) as (Fund)
(Technical) as (Tech)
(Account) as (Acc)
(Other) as (Othr)
(Strategy) as (Str)
(Indicator) as (Ind)

(Gath) --> (Tech) : 0..1
(Gath) --> (Fund) : 0..1
(Gath) --> (Othr) : 0..n
(Ord) -> (Gath) : 0..1
(Acc) --> (Gath) : 0..n
(Acc) --> (Ord) : 0..n
(Fund) --> (Str) : 0..n
(Fund) --> (Ind) : 0..n

note right of (Acc)
  Account contains
  a bot internally.
  Bot can be optionally activated.
end note

note right of (Gath)
  Gatherer is a collection
  of results of technical,
  fundamental and other kinds of analysis
end note

'Admin ---> (Use) : 0to1

'note "This note is connected\nto several objects." as N2
'(Start) .. N2
'N2 .. (Use)
@enduml