@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant Technical as tech
collections Strategies as str


activate str
alt active
str -> tech : Fetch last candle
str -> str : Update current\n value of strategy
else created or deactivated
str -> tech : Fetch buffer of candles
str -> str : Calculate new value
end alt
str -> tech : return result
@enduml