@startuml
'https://plantuml.com/state-diagram
hide empty description

[*] --> Created
Created --> Feeded
Feeded --> Calculating
Calculating --> WithResult
WithResult --> Deactivated
WithResult -> Feeded
Deactivated --> Removed
Deactivated -> Reactivated
Reactivated -> Feeded
Removed --> [*]
WithResult : pass result to Strategies\n and/or to Technical
@enduml