@startuml
'https://plantuml.com/state-diagram
hide empty description

[*] --> Created
Created --> Feeded
Feeded --> Calculating
Calculating --> WithResult
WithResult --> Deactivated
Modified <-- WithResult
Modified -> Created
WithResult -> Feeded
Deactivated --> Removed
Deactivated -> Reactivated
Reactivated -> Feeded
Removed --> [*]
WithResult : ready to pass information\n to Gatherer
@enduml