@startuml
'https://plantuml.com/state-diagram
hide empty description

 [*] -> NecessaryCandlesGathered
 NecessaryCandlesGathered --> BasicIndicatorsCalculated
 BasicIndicatorsCalculated --> StrategiesCalculated
 StrategiesCalculated --> AggregationOfStrategies
 AggregationOfStrategies -> NextCandleGathering : auto-update values
 NextCandleGathering --> BasicIndicatorsCalculated
AggregationOfStrategies : has calculated output, can share
AggregationOfStrategies : data to Gatherer
@enduml